const GET_ENTERPRISE_BY_ID_FULFILLED = "GET_ENTERPRISE_BY_ID_FULFILLED"
const GET_ENTERPRISE_BY_ID_REJECTED = "GET_ENTERPRISE_BY_ID_REJECTED"
const GET_ENTERPRISES_FULFILLED = "GET_ENTERPRISES_FULFILLED"
const GET_ENTERPRISES_REJECTED = "GET_ENTERPRISES_REJECTED"
const GET_ENTERPRISES_NAME_OR_TYPE_FULFILLED = "GET_ENTERPRISES_NAME_OR_TYPE_FULFILLED"
const GET_ENTERPRISES_NAME_OR_TYPE_REJECTED = "GET_ENTERPRISES_NAME_OR_TYPE_REJECTED"

export {
    GET_ENTERPRISE_BY_ID_FULFILLED,
    GET_ENTERPRISE_BY_ID_REJECTED,
    GET_ENTERPRISES_FULFILLED,
    GET_ENTERPRISES_REJECTED,
    GET_ENTERPRISES_NAME_OR_TYPE_FULFILLED,
    GET_ENTERPRISES_NAME_OR_TYPE_REJECTED,
}