const GET_ENTERPRISE_BY_ID_FULFILLED = "GET_ENTERPRISE_BY_ID_FULFILLED"
const GET_ENTERPRISE_BY_ID_REJECTED = "GET_ENTERPRISE_BY_ID_REJECTED"
const GET_ENTERPRISES_FULFILLED = "GET_ENTERPRISES_FULFILLED"
const GET_ENTERPRISES_REJECTED = "GET_ENTERPRISES_REJECTED"

export { GET_ENTERPRISE_BY_ID_FULFILLED, GET_ENTERPRISE_BY_ID_REJECTED, GET_ENTERPRISES_FULFILLED, GET_ENTERPRISES_REJECTED }