const POST_SIGN_IN_FULFILLED = "POST_SIGN_IN_FULFILLED"
const POST_SIGN_IN_REJECTED = "POST_SIGN_IN_REJECTED"
const SET_SAVE_HEADER = "SET_SAVE_HEADER"

export { POST_SIGN_IN_FULFILLED, POST_SIGN_IN_REJECTED, SET_SAVE_HEADER, }